name: amap_base
description: AMap flutter plugin, base dependency library.
version: 1.0.0+1
homepage: https://lbs.amap.com/

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


