name: Publish to Pub.dev

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main # required!

      - name: ">> Dart package <<"
        id: package_publisher
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          skipTests: true
          flutter: true
          force: true

      - name: Create Release
        if: steps.package_publisher.outputs.success == 'true'
        uses: kuloud/Github-Release-Action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package_publisher.outputs.localVersion }}
          title: Release ${{ steps.package_publisher.outputs.localVersion }}
          body: |
            Automated release for version ${{ steps.package_publisher.outputs.localVersion }}
          draft: false
          prerelease: false
